# Stages ----------------------------------------------------------------------
stages:
    - build

# Before Script ---------------------------------------------------------------
before_script:
    - export DATE=$(date +"%Y-%m-%d")

# Job templates ---------------------------------------------------------------
.job_template_build:
    stage: build
    variables:
        DOCKER_DRIVER: overlay2
        NO_CACHE: "true"
        CONTEXT_DIR: "./"
        DOCKERFILE_DIR: "./"
        IMAGE_NAME: treemaker
    tags:
        - docker-privileged-xl
    image:
        name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
        entrypoint: [""]
    script:
        # Build and push the image from the Dockerfile at the root of the project.
        # To push to a specific docker tag, amend the --destination parameter, e.g. --destination $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
        # See https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference for available variables
        - echo "Pipeline source - $CI_PIPELINE_SOURCE"
        - echo "Base image - $BASE_IMAGE"
        - echo "Building Docker image with TreeMaker and ServiceX dependencies on ${DATE}"
        - echo ${CI_PROJECT_DIR}/${CONTEXT_DIR}/
        - ls -alh ${CI_PROJECT_DIR}/${CONTEXT_DIR}/
        - echo "Logging into the registry ${CI_REGISTRY}"
        - export DOCKER_AUTH="$(echo -n $DOCKER_USERNAME:$DOCKER_PASSWORD | base64)" # https://github.com/GoogleContainerTools/kaniko#pushing-to-docker-hub
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}, \"${DOCKER_REGISTRY}\":{\"auth\":\"${DOCKER_AUTH}\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context ${CI_PROJECT_DIR}/${CONTEXT_DIR} --dockerfile ${CI_PROJECT_DIR}/${DOCKERFILE_DIR}/Dockerfile --destination "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${BRANCH_NAME}-${SUFFIX}" --destination "${DOCKER_GROUP}/${IMAGE_NAME}:${BRANCH_NAME}-${SUFFIX}" --build-arg=BUILD_DATE="${DATE}" --build-arg=VERSION="${DATE}" --build-arg=VCS_URL="${CI_REPOSITORY_URL}" --build-arg=VCS_REF="${CI_COMMIT_SHORT_SHA}" --build-arg=BASEIMAGE="${BASE_IMAGE}" --build-arg=DOWNLOAD_URL="${DOWNLOAD_URL}" --build-arg=FILE_NAME="${FILE_NAME}" --build-arg=CMSSW_VERSION="${CMSSW_VERSION}"

# Jobs/Includes ---------------------------------------------------------------
build_treemaker_Run2_2017-servicex:
    extends: .job_template_build
    variables:
        DOCKER_GROUP: treemaker
        DOCKER_REGISTRY: https://index.docker.io/v1/
        BRANCH_NAME: Run2_2017
        SUFFIX: servicex
        BASE_IMAGE: gitlab-registry.cern.ch/treemaker/treemaker/treemaker:Run2_2017-standalone
        DOWNLOAD_URL: https://cernbox.cern.ch/index.php/s/DsfTPyDEgCjTmBQ/download
        FILE_NAME: eos.opendata.cms.MonteCarlo2016.RunIISummer16MiniAODv2.QCD_Pt_600to800_TuneCUETP8M1_13TeV_pythia8.MINIAODSIM.PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1.70000.0048131D-3CB3-E611-813A-001E67DFFB31_100evt.root
        CMSSW_VERSION: CMSSW_10_2_21

